### PR TITLE
Fix build against VTK9

### PR DESCRIPTION
**Pull request by jcfr**
This pull request is intended to address issues reported in
https://slicer.cdash.org/index.php?project=SlicerPreview&date=2021-05-18&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=SPHARM-PDM

Slicer migration guide has been updated accordingly.

See https://www.slicer.org/w/index.php?title=Documentation/Nightly/Developers/Tutorials/MigrationGuide#Slicer_5.0:_Supporting_both_VTK_8.0_and_VTK_9.0

### CODE REVIEW

**Comment by jcfr** [comment]
cc: @allemangD

**Comment by jcfr** [comment]
This should be ported to https://github.com/slicersalt/SPHARM-PDM/tree/slicersalt-2020-04-27-47188484c

Cc: @allemangD @bpaniagua

**Comment by jcfr** [comment]
> Wouldnt this change be updated automatically since we are pulling SPHARM as a dependency as soon as this PR is merged?

Since SlilcerSALT is built against a specific version of `SPHARM-PDM` (see below), someone should assess if updating it as well is sensible:

https://github.com/Kitware/SlicerSALT/blob/345f48977013b4cfa8a3c3f9240cb27bfb0ea77a/CMakeLists.txt#L382-L388

**Comment by bpaniagua** [comment]
Missed that. Well we need to merge this PR and then update the SlicerSALT mirror.

**Review by bpaniagua — APPROVED** [review]
lgtm

**Pull request merged**
